[package]
name = "unifed-fedlearner"
version = "0.0.0"
keywords = ["federated learning", "machine learning"]
description = "Integrating Fedlearner framework into UniFed as a CoLink protocol."
language = "python"
install_script = """
if { conda env list | grep 'colink-protocol-unifed-fedlearner'; } >/dev/null 2>&1; then
    conda env remove -n colink-protocol-unifed-fedlearner
fi
conda create -n colink-protocol-unifed-fedlearner python=3.9 -y
conda activate colink-protocol-unifed-fedlearner
git clone https://github.com/adap/flower.git
cd flower
cd ..
"""
entrypoint = """
conda activate colink-protocol-unifed-fedlearner
"""
